js {
  const params = require("definitions/env_var.js");
  const parameter1 = params.project_id;
  const parameter2 = params.db_schenker_dataset_name;
  const parameter3 = params.nordea_p_ver_num;
}

config {
  type: "operations",
  description: "Job for db_schenker"
}

DECLARE param INT64 DEFAULT CAST(${parameter3} AS INT64);

BEGIN
  CALL `cobundu-bi-playground.mcs_procedures.mcs_stream_22`('${parameter1}', '${parameter2}',param);
END;