config {
  type: "view",
  schema: dataform.projectConfig.vars.transformation_target_tenant_dataset,
  tags: ["axxerion"],
  labels: {
    layer: "intermediate_views",
    domain: "reservables",
    managed_by: "dataform"
  }
}

SELECT
    reso.reso_id AS reservable_id,
    reso.reso_unique_reference,
    reso.reso_reference AS reservable_reference,
    reso.reso_name AS reservable_name,
    reso.reso_type AS reservable_type,
    loc.location_id,
    loc.loc_type AS location_class,
    loc.loc_parent_id AS parent_location_id,
    CASE
        WHEN loc.loc_type = 'WORKPLACE' THEN 'ROOM'
        WHEN loc.loc_type IN ('ROOM', 'PARKING') THEN 'FLOOR'
    END AS parent_location_class,
    loc.loc_building_id AS building_id,
    loc.loc_floor_id AS floor_id,
    reso.reso_tz_iana_timezone AS time_zone
FROM ${ref('IWMS_RESERVABLES')} AS reso
INNER JOIN ${ref('DIM_LOCATIONS')} AS loc
    ON (
        reso.reso_type = 'ROOM'
        AND reso.reso_objectid = loc.loc_room_id
        AND loc.loc_type = 'ROOM'
    )
    OR (
        reso.reso_type = 'WORKPLACE'
        AND reso.reso_objectid = loc.loc_workplace_id
        AND loc.loc_type = 'WORKPLACE'
    )
    OR (
        reso.reso_type = 'PARKING'
        AND reso.reso_objectid = loc.loc_parking_id
        AND loc.loc_type = 'PARKING'
    )
WHERE reso.reso_type IN ('ROOM', 'WORKPLACE', 'PARKING')
