config {
  type: "table",
  schema: dataform.projectConfig.vars.transformation_target_tenant_dataset,
  tags: ["axxerion"],
  name: "reservables",
  //columns: columns_description.getColumnsDescriptions("reservables"),
  bigquery: {
    labels: {
      layer: "intermediate_tables",
      domain: "reservables",
      managed_by: "dataform"
    }
  }
}

SELECT
    reservable.id,
    reservable.reference,
    reservable.uniquereference,
    reservable.objectnameid,
    reservable.propertyid,
    reservable.clientid,
    t1area.id AS area_id,
    t1area.floorareaid AS floor_area_id,
    t1area.capacity AS area_capacity,
    t1area.areatypecode,
    t1area.categoryfolderid AS area_categoryfolderid,
    t1area.name AS area_name,
    asset.id AS asset_id,
    asset.propertyid AS asset_propertyid,
    asset.quantity AS asset_quantity,
    asset.categoryfolderid AS asset_categoryfolderid,
    asset.name AS asset_name,
    catalogitem.id AS catalogitem_id,
    catalogitem.categoryfolderid AS catalogitem_categoryfolderid,
    catalogitem.name AS catalogitem_name,
    area_category_folder.name AS area_category_folder_name,
    area_category_folder.reference AS area_category_folder_reference,
    asset_folder.name AS asset_folder_name,
    asset_folder.reference AS asset_folder_reference,
    catalogitem_folder.name AS catalogitem_folder_name,
    catalogitem_folder.reference AS catalogitem_folder_reference,
    objectname.name AS objectname_name,
    -- Name information based on objectnameid
    CASE
        WHEN reservable.objectnameid = 50 THEN t1area.name
        WHEN reservable.objectnameid = 3 THEN asset.name
        WHEN reservable.objectnameid = 63 THEN catalogitem.name
    END AS object_name,
    CASE
        WHEN reservable.objectnameid = 50 THEN t1area.id
        WHEN reservable.objectnameid = 3 THEN asset.id
        WHEN reservable.objectnameid = 63 THEN catalogitem.id
    END AS object_id,
    -- Capacity information based on objectnameid
    CASE
        WHEN reservable.objectnameid = 50 THEN CAST(t1area.capacity AS INT64)
        WHEN reservable.objectnameid = 3 THEN CAST(asset.quantity AS INT64)
        WHEN reservable.objectnameid = 63 THEN 1
    END AS item_object_capacity,
    -- Type information based on objectnameid
    CASE
        WHEN reservable.objectnameid = 50
            THEN
                CASE
                    WHEN t1area.areatypecode = 1 THEN "FLOOR"
                    WHEN t1area.areatypecode = 2 THEN "ROOM"
                    WHEN t1area.areatypecode = 3 THEN "WORKPLACE"
                    WHEN t1area.areatypecode = 5 THEN "BUILDING"
                    WHEN t1area.areatypecode = 9 THEN "PARKING"
                END
        WHEN reservable.objectnameid = 3 THEN "EQUIPMENT"
        WHEN reservable.objectnameid = 63 THEN "SERVICE"
    END AS item_type,
    -- Category information
    CASE
        WHEN reservable.objectnameid = 50 THEN area_category_folder.name
        WHEN reservable.objectnameid = 3 THEN asset_folder.name
        WHEN reservable.objectnameid = 63 THEN catalogitem_folder.name
    END AS item_object_category_name,
    -- Category reference based on objectnameid
    CASE
        WHEN reservable.objectnameid = 50 THEN area_category_folder.reference
        WHEN reservable.objectnameid = 3 THEN asset_folder.reference
        WHEN reservable.objectnameid = 63 THEN catalogitem_folder.reference
    END AS item_object_category_reference,
    CASE
        WHEN reservable.objectnameid = 50 THEN t1area.reservable = 1
        WHEN reservable.objectnameid = 3 THEN asset.reservable = 1
        WHEN reservable.objectnameid = 63 THEN catalogitem.reservable = 1
    END AS is_reservable,
    GREATEST(
        COALESCE(reservable.updatetime, DATETIME("1970-01-01 00:00:00")),
        COALESCE(t1area.updatetime, DATETIME("1970-01-01 00:00:00")),
        COALESCE(asset.updatetime, DATETIME("1970-01-01 00:00:00")),
        COALESCE(catalogitem.updatetime, DATETIME("1970-01-01 00:00:00")),
        COALESCE(area_category_folder.updatetime, DATETIME("1970-01-01 00:00:00")),
        COALESCE(asset_folder.updatetime, DATETIME("1970-01-01 00:00:00")),
        COALESCE(catalogitem_folder.updatetime, DATETIME("1970-01-01 00:00:00")),
        COALESCE(objectname.updatetime, DATETIME("1970-01-01 00:00:00"))
    ) AS updatetime
FROM
    ${ref('reservable')} AS reservable
LEFT JOIN
    ${ref('area')} AS t1area
    ON
        reservable.instanceid = t1area.id
        AND t1area.binentryid = 0
LEFT JOIN
    ${ref('asset')} AS asset
    ON
        reservable.instanceid = asset.id
        AND asset.binentryid = 0
LEFT JOIN
    ${ref('catalogitem')} AS catalogitem
    ON
        reservable.instanceid = catalogitem.id
        AND catalogitem.binentryid = 0
LEFT JOIN
    ${ref('folder')} AS area_category_folder
    ON
        t1area.categoryfolderid = area_category_folder.id
        AND area_category_folder.binentryid = 0
LEFT JOIN
    ${ref('folder')} AS asset_folder
    ON asset.categoryfolderid = asset_folder.id
LEFT JOIN
    ${ref('folder')} AS catalogitem_folder
    ON catalogitem.categoryfolderid = catalogitem_folder.id
LEFT JOIN
    ${ref('objectname')} AS objectname
    ON
        reservable.objectnameid = objectname.id
        AND objectname.binentryid = 0
WHERE
    reservable.clientid = ${dataform.projectConfig.vars.client_id}  -- noqa: PRS, LXR, LT02
    AND reservable.binentryid = 0
