// Shared descriptions that can be reused across schemas
const sharedDescriptions = {
  // IDs
  reservation_id: "immutable database identifier of a reservation (primary key)",
  item_id: "immutable database identifier of a reservation item (primary key)",
  reservable_id: "unique identifier of reservable (primary key)",
  building_id: "identifier of building",
  floor_id: "identifier of floor",

  // Names
  organizer_organization_name: "organization name of the persons for who the reservation is for (accountable)",
  creator_organisation_name: "organization name of the person who created a reservation",

  // References
  unique_reference: "globally unique reference of a reservation",
  user_reference: "reservation reference for the user (booking number)",
  item_object_reference: "unique reference of an item in a reservation",
  reso_unique_reference: "globally unique reference of reservable",
  reso_reference: "reservable reference for the user",

  // Building & Floor
  building_name: "name of building",
  building_reference: "reference of building",
  floor_name: "name of floor",
  floor_reference: "reference of floor",

  // Reservable - Capacity
  capacity: "capacity (number of persons) of the reservable",

  // Result
  result: "result of the reservation process: RESERVED / CANCELLED / NO_SHOW / COMPLETED",

  // DWH fields
  dwh_modified_timestamp: "timestamp when modified in dwh",

  // Timeslots - Time & Date
  timeslot_id: "unique identifier of a timeslot (primary key), combination of location_id & timeslot_start",
  calendar_date: "calendar date in ISO 8601 format",
  day_of_week: "integer value between 1 (Monday) and 7 (Sunday)",
  calendar_datetime: "date + time that represents the timeslot in local time (in ISO 8601 format)",
  timeslot_start: "same as calendar_datetime but as a string and including time zone (of the building)",
  hour_of_day: "integer value between 0 (1st hour) to 23 (last hour)",
  creation_timestamp: "technical timestamp when the row was created, in ISO 8601 format and always in UTC",

  // Timeslots - Location & Space
  ts_location_id: "identifier of a location (foreign key)",
  location_class: "class of location",
  parent_location_class: "class of parent location",
  space_class: "class of space (WORK, MEETING, FOCUS, PARKING, SANITARY, OTHER, ALL)",

  // Timeslots - Location Metrics
  locations_total: "number of sublocations that exist",
  locations_occupancy_monitored: "number of sublocations with occupancy sensor",
  locations_occupied: "number of sublocations that are occupied during the timeslot",
  rooms_total: "number of rooms in total, including the ones that are not monitored",
  rooms_occupancy_monitored: "number of rooms with occupancy sensor",
  workplaces_total: "number of workplaces in total, including the ones that are not monitored",
  workplaces_occupancy_monitored: "number of workplaces with occupancy sensor",

  // Timeslots - Occupancy Metrics
  occupancy_data_class: "data class of occupancy sensor",
  presence: "is always 1 (occupied) or 0 (not occupied) per timeslot",
  headcount_peak: "highest headcount registered during the timeslot",
  headcount_low: "lowest headcount registered during the timeslot",
  headcount_average: "average headcount registered during the timeslot",
  utilization_time: "number of hours that the space was occupied in the timeslot",

  // Timeslots - Business Hours
  business_day_start_hour: "start of business day (time value)",
  business_day_end_hour: "end of business day (time value)",

  // Timeslots - Sensor Data Specific
  headcount_count: "count of headcount readings during the timeslot",

  // Timeslots - Daily Metrics
  utilization_score: "utilization rate x efficiency rate, per timeslot",
  dwell_time_average: "average uninterrupted hours of presence, per day",
  dwell_time_longest: "highest uninterrupted hours of presence, per day",
  dwell_time_shortest: "lowest uninterrupted hours of presence, per day",

  // Timeslots - Rate Metrics (15m)
  utilization_rate_15m: "number of hours that the space was occupied in the timeslot, divided by 0,25h (utilization_time/0.25), rounded to 2 decimals",
  efficiency_rate_15m: "average headcount divided by capacity (headcount_average/capacity), rounded to 2 decimals",
  occupancy_rate_15m: "locations_occupied divided by locations_occupancy_monitored (locations_occupied/locations_occupancy_monitored), rounded to 2 decimals",

  // Timeslots - Rate Metrics (avg/peak/low)
  utilization_rate_avg: "average utilization_rate during this timeslot",
  utilization_rate_peak: "highest utilization_rate during this timeslot",
  utilization_rate_low: "lowest utilization_rate during this timeslot",
  efficiency_rate_avg: "average efficiency_rate during this timeslot",
  efficiency_rate_peak: "highest efficiency_rate during this timeslot",
  efficiency_rate_low: "lowest efficiency_rate during this timeslot",
  occupancy_rate_avg: "average occupancy_rate during this timeslot",
  occupancy_rate_peak: "highest occupancy_rate during this timeslot",
  occupancy_rate_low: "lowest occupancy_rate during this timeslot",

  // Timeslots - Capacity
  ts_capacity: "capacity (number of seats) of the location",

  // Location hierarchy
  location_id: "unique identifier of a location (primary key)",
  parent_location_id: "identifier of parent location",
  loc_name: "name of location",
  location_reference: "reference of location",
  area_name: "name of area",
  area_reference: "reference of area",
  site_name: "name of site",
  site_reference: "reference of site",
  room_name: "name of room",
  room_reference: "reference of room",
  workplace_name: "name of workplace",
  workplace_reference: "reference of workplace",
  parking_place_name: "name of parking place",
  parking_place_reference: "reference of parking place",

  // Common IDs
  area_id: "identifier of area",
  site_id: "identifier of site",
  room_id: "identifier of room",
  workplace_id: "identifier of workplace",
  parking_place_id: "identifier of parking place",

  // Common codes
  area_code: "code of area",
  site_code: "code of site",
  room_code: "code of room",
  workplace_code: "code of workplace",
  parking_place_code: "code of parking place",
  building_code: "code of building",
  floor_code: "code of floor",

  // Common flags and metadata
  record_date: "date when record was created",
  is_custom: "flag if record is custom",
  is_reservable: "flag if location is reservable",

  // Sensor data IDs & Type
  sensor_id: "unique identifier of a device sensor",
  device_id: "unique identifier of a device",
  sensor_type: "what data a sensor monitors (PRESENCE / HEADCOUNT / CO2 etc)",
};

const schemas = {
  // Tables from definitions/axxerion/ (in alphabetical order as per directory listing)
  DIM_LOCATIONS: {
    etl_start_date: "etl batch start date",
    loc_flr_bld: "concatenated building and floor names of a location",
    location_id: sharedDescriptions.location_id,
    loc_type: "type of location",
    loc_svg_location_id: "identifier of svg location",
    loc_is_reservable: sharedDescriptions.is_reservable,
    loc_city: "city where location is located",
    loc_zip_code: "zip code of location",
    loc_street_nr: "street and number of location",
    loc_country: "country where location is located",
    loc_area_sqm: "area of location in square meters",
    loc_drawing_area_sqm: "drawing area of location in square meters",
    loc_parent_id: sharedDescriptions.parent_location_id,
    loc_region_code: "code of region",
    loc_region: "name of region",
    loc_out_of_use: "flag if location is out of use",
    loc_area_id: sharedDescriptions.area_id,
    loc_area_code: sharedDescriptions.area_code,
    loc_area: sharedDescriptions.area_name,
    loc_site_id: sharedDescriptions.site_id,
    loc_site_code: sharedDescriptions.site_code,
    loc_site: sharedDescriptions.site_name,
    loc_building_id: sharedDescriptions.building_id,
    loc_building_code: sharedDescriptions.building_code,
    loc_building: sharedDescriptions.building_name,
    loc_floor_id: sharedDescriptions.floor_id,
    loc_floor_code: sharedDescriptions.floor_code,
    loc_floor: sharedDescriptions.floor_name,
    loc_room_id: sharedDescriptions.room_id,
    loc_room_code: sharedDescriptions.room_code,
    loc_room: sharedDescriptions.room_name,
    loc_workplace_id: sharedDescriptions.workplace_id,
    loc_workplace_code: sharedDescriptions.workplace_code,
    loc_workplace: sharedDescriptions.workplace_name,
    loc_parking_id: sharedDescriptions.parking_place_id,
    loc_parking_code: sharedDescriptions.parking_place_code,
    loc_parking: sharedDescriptions.parking_place_name,
    loc_room_category_id: "identifier of room category",
    loc_room_category: "name of room category",
    loc_space_category: "name of space category",
    loc_aggregation_lvl: "aggregation level for location",
    sc_flag: "space category flag",
    loc_room_nr_workplaces: "number of workplaces in room",
    loc_room_max_quiet: "maximum quiet capacity of room",
    loc_room_max_crowded: "maximum crowded capacity of room",
    loc_name: sharedDescriptions.loc_name,
    loc_code: sharedDescriptions.location_reference,
  },
  IWMS_RESERVABLES: {
    reso_reference: sharedDescriptions.reso_reference,
    reso_unique_reference: sharedDescriptions.reso_unique_reference,
    reso_type: "type of reservable (FLOOR, ROOM, WORKPLACE, BUILDING, PARKING, EQUIPMENT, SERVICE)",
    reso_name: "name of reservable",
    reso_capacity: sharedDescriptions.capacity,
    reso_categoryname: "name of reservable category",
    reso_categoryreference: "reference of reservable category",
    reso_id: sharedDescriptions.reservable_id,
    reso_objectnameid: "identifier of object name (always 352 for reservables)",
    reso_propertyid: "identifier of property",
    reso_building_id: sharedDescriptions.building_id,
    reso_buildingreference: sharedDescriptions.building_reference,
    reso_buildingname: sharedDescriptions.building_name,
    reso_tz_iana_timezone: "identifier of iana timezone",
    reso_tz_utc_offset_dst: "utc offset during daylight saving time",
    reso_tz_abbreviation_dst: "timezone abbreviation during daylight saving time",
    reso_objectid: "object identifier based on type (AREA, ASSET, or CATALOGITEM)",
    reso_objecttype: "name of object type",
    reso_floorid: sharedDescriptions.floor_id,
    reso_floorreference: sharedDescriptions.floor_reference,
    reso_floorname: sharedDescriptions.floor_name,
    reso_status: "status of reservable (ACTIVE)",
    last_modified_timestamp: sharedDescriptions.dwh_modified_timestamp,
  },
  IWMS_RESERVATIONS: {
    res_userreference: sharedDescriptions.user_reference,
    res_reference: sharedDescriptions.unique_reference,
    res_subject: "subject/title of reservation",
    res_description: "description of reservation",
    res_statuscode: "status code of reservation",
    res_statusname: "name of reservation status",
    res_building_id: sharedDescriptions.building_id,
    res_buildingreference: sharedDescriptions.building_reference,
    res_buildingname: sharedDescriptions.building_name,
    res_organizerorganizationname: sharedDescriptions.organizer_organization_name,
    res_creatororganizationname: sharedDescriptions.creator_organisation_name,
    res_itemnr: "sequential number of item in a reservation (01, 02, 03 etc)",
    res_itemobjectreference: sharedDescriptions.item_object_reference,
    res_itemname: "name of reserved item",
    res_itemdescription: "description of reserved item",
    res_itemtype: "type of reserved item",
    res_itemobjectcategoryname: "name of reserved item object category",
    res_itemobjectcategoryreference: "reference of reserved item object category",
    res_id: sharedDescriptions.reservation_id,
    res_objectnameid: "identifier of object name",
    res_itemid: sharedDescriptions.item_id,
    res_itemquantity: "quantity of reserved item",
    res_itemcapacity: "capacity of reserved item",
    res_starttimestamp: "start date and time of reservation in local timezone",
    res_endtimestamp: "end date and time of reservation in local timezone",
    res_createtimestamp: "creation date and time of reservation in local timezone",
    res_canceltimestamp: "cancellation date and time of reservation in local timezone",
    res_updatetimestamp: "last update date and time of reservation in local timezone",
    res_noshow: "flag if reservation was marked as no-show (1/0)",
    res_updatetime: "last update date and time used for incremental processing",
    res_tz_iana_timezone: "iana time zone identifier for reservation",
    res_nrofparticipants: "number of participants",
    res_result: sharedDescriptions.result,
    res_stage: "reservation stage (P=Planned, C=Current, H=Historical)",
    last_modified_timestamp: sharedDescriptions.dwh_modified_timestamp,
    is_deleted: "flag if reservation was deleted (Y/N)",
  },
  qsdb_tenantsettings: {
    setting: "tenant setting name",
    value: "value of tenant setting",
  },
  qsdb_translation: {
    index: "translation index identifier",
    objects: "translation object type",
    english: "english translation text",
    dutch: "dutch translation text",
    french: "french translation text",
    german: "german translation text",
    swedish: "swedish translation text",
    record_date: sharedDescriptions.record_date,
    is_custom: sharedDescriptions.is_custom,
    spanish: "spanish translation text",
  },
  qsdb_variables: {
    id: "identifier of variable",
    variable_name: "name of variable",
    variable_value: "value of variable",
    report_name: "name of report using this variable",
    record_date: sharedDescriptions.record_date,
    is_custom: sharedDescriptions.is_custom,
  },
  timeslots_15m_occupancy_data: {
    timeslot_id: sharedDescriptions.timeslot_id,
    calendar_date: sharedDescriptions.calendar_date,
    day_of_week: sharedDescriptions.day_of_week,
    calendar_datetime: sharedDescriptions.calendar_datetime,
    timeslot_start: sharedDescriptions.timeslot_start,
    hour_of_day: sharedDescriptions.hour_of_day,
    creation_timestamp: sharedDescriptions.creation_timestamp,
    location_id: sharedDescriptions.ts_location_id,
    location_class: sharedDescriptions.location_class,
    parent_location_id: sharedDescriptions.parent_location_id,
    parent_location_class: sharedDescriptions.parent_location_class,
    building_id: sharedDescriptions.building_id,
    floor_id: sharedDescriptions.floor_id,
    space_class: sharedDescriptions.space_class,
    capacity: sharedDescriptions.ts_capacity,
    locations_total: sharedDescriptions.locations_total,
    locations_occupancy_monitored: sharedDescriptions.locations_occupancy_monitored,
    locations_occupied: sharedDescriptions.locations_occupied,
    rooms_total: sharedDescriptions.rooms_total,
    rooms_occupancy_monitored: sharedDescriptions.rooms_occupancy_monitored,
    workplaces_total: sharedDescriptions.workplaces_total,
    workplaces_occupancy_monitored: sharedDescriptions.workplaces_occupancy_monitored,
    occupancy_data_class: sharedDescriptions.occupancy_data_class,
    presence: sharedDescriptions.presence,
    headcount_peak: sharedDescriptions.headcount_peak,
    headcount_low: sharedDescriptions.headcount_low,
    headcount_average: sharedDescriptions.headcount_average,
    headcount_count: sharedDescriptions.headcount_count,
    utilization_time: sharedDescriptions.utilization_time,
    utilization_rate: sharedDescriptions.utilization_rate_15m,
    efficiency_rate: sharedDescriptions.efficiency_rate_15m,
    occupancy_rate: sharedDescriptions.occupancy_rate_15m,
    business_day_start_hour: sharedDescriptions.business_day_start_hour,
    business_day_end_hour: sharedDescriptions.business_day_end_hour,
  },
  timeslots_1h_occupancy_data: {
    timeslot_id: sharedDescriptions.timeslot_id,
    calendar_date: sharedDescriptions.calendar_date,
    day_of_week: sharedDescriptions.day_of_week,
    calendar_datetime: sharedDescriptions.calendar_datetime,
    timeslot_start: sharedDescriptions.timeslot_start,
    hour_of_day: sharedDescriptions.hour_of_day,
    creation_timestamp: sharedDescriptions.creation_timestamp,
    location_id: sharedDescriptions.ts_location_id,
    location_class: sharedDescriptions.location_class,
    parent_location_id: sharedDescriptions.parent_location_id,
    parent_location_class: sharedDescriptions.parent_location_class,
    building_id: sharedDescriptions.building_id,
    floor_id: sharedDescriptions.floor_id,
    space_class: sharedDescriptions.space_class,
    capacity: sharedDescriptions.ts_capacity,
    locations_total: sharedDescriptions.locations_total,
    locations_occupancy_monitored: sharedDescriptions.locations_occupancy_monitored,
    locations_occupied: sharedDescriptions.locations_occupied,
    rooms_total: sharedDescriptions.rooms_total,
    rooms_occupancy_monitored: sharedDescriptions.rooms_occupancy_monitored,
    workplaces_total: sharedDescriptions.workplaces_total,
    workplaces_occupancy_monitored: sharedDescriptions.workplaces_occupancy_monitored,
    occupancy_data_class: sharedDescriptions.occupancy_data_class,
    presence: sharedDescriptions.presence,
    headcount_peak: sharedDescriptions.headcount_peak,
    headcount_low: sharedDescriptions.headcount_low,
    headcount_average: sharedDescriptions.headcount_average,
    headcount_count: sharedDescriptions.headcount_count,
    utilization_time: sharedDescriptions.utilization_time,
    utilization_rate: sharedDescriptions.utilization_rate_avg,
    utilization_rate_peak: sharedDescriptions.utilization_rate_peak,
    utilization_rate_low: sharedDescriptions.utilization_rate_low,
    efficiency_rate: sharedDescriptions.efficiency_rate_avg,
    efficiency_rate_peak: sharedDescriptions.efficiency_rate_peak,
    efficiency_rate_low: sharedDescriptions.efficiency_rate_low,
    occupancy_rate: sharedDescriptions.occupancy_rate_avg,
    occupancy_rate_peak: sharedDescriptions.occupancy_rate_peak,
    occupancy_rate_low: sharedDescriptions.occupancy_rate_low,
    business_day_start_hour: sharedDescriptions.business_day_start_hour,
    business_day_end_hour: sharedDescriptions.business_day_end_hour,
  },
  timeslots_1d_occupancy_data: {
    timeslot_id: sharedDescriptions.timeslot_id,
    calendar_date: sharedDescriptions.calendar_date,
    day_of_week: sharedDescriptions.day_of_week,
    calendar_datetime: sharedDescriptions.calendar_datetime,
    timeslot_start: sharedDescriptions.timeslot_start,
    creation_timestamp: sharedDescriptions.creation_timestamp,
    location_id: sharedDescriptions.ts_location_id,
    location_class: sharedDescriptions.location_class,
    parent_location_id: sharedDescriptions.parent_location_id,
    parent_location_class: sharedDescriptions.parent_location_class,
    building_id: sharedDescriptions.building_id,
    floor_id: sharedDescriptions.floor_id,
    space_class: sharedDescriptions.space_class,
    capacity: sharedDescriptions.ts_capacity,
    locations_total: sharedDescriptions.locations_total,
    locations_occupancy_monitored: sharedDescriptions.locations_occupancy_monitored,
    locations_occupied: sharedDescriptions.locations_occupied,
    rooms_total: sharedDescriptions.rooms_total,
    rooms_occupancy_monitored: sharedDescriptions.rooms_occupancy_monitored,
    workplaces_total: sharedDescriptions.workplaces_total,
    workplaces_occupancy_monitored: sharedDescriptions.workplaces_occupancy_monitored,
    occupancy_data_class: sharedDescriptions.occupancy_data_class,
    presence: sharedDescriptions.presence,
    headcount_peak: sharedDescriptions.headcount_peak,
    headcount_low: sharedDescriptions.headcount_low,
    headcount_average: sharedDescriptions.headcount_average,
    headcount_count: sharedDescriptions.headcount_count,
    utilization_time: sharedDescriptions.utilization_time,
    utilization_rate: sharedDescriptions.utilization_rate_avg,
    utilization_rate_peak: sharedDescriptions.utilization_rate_peak,
    utilization_rate_low: sharedDescriptions.utilization_rate_low,
    efficiency_rate: sharedDescriptions.efficiency_rate_avg,
    efficiency_rate_peak: sharedDescriptions.efficiency_rate_peak,
    efficiency_rate_low: sharedDescriptions.efficiency_rate_low,
    occupancy_rate: sharedDescriptions.occupancy_rate_avg,
    occupancy_rate_peak: sharedDescriptions.occupancy_rate_peak,
    occupancy_rate_low: sharedDescriptions.occupancy_rate_low,
    utilization_score: sharedDescriptions.utilization_score,
    dwell_time_average: sharedDescriptions.dwell_time_average,
    dwell_time_longest: sharedDescriptions.dwell_time_longest,
    dwell_time_shortest: sharedDescriptions.dwell_time_shortest,
    business_day_start_hour: sharedDescriptions.business_day_start_hour,
    business_day_end_hour: sharedDescriptions.business_day_end_hour,
  },
  TS1H_RESERVATIONS: {
    ts_itemreference: sharedDescriptions.item_object_reference,
    ts_userreference: sharedDescriptions.user_reference,
    ts_resid: sharedDescriptions.reservation_id,
    ts_itemid: sharedDescriptions.item_id,
    ts_nrofparticipants: "number of participants in a reservation",
    ts_itemname: "name of reserved item",
    ts_itemtype: "type of reserved item",
    ts_itemquantity: "quantity of reserved item",
    ts_datetime: "timestamp of hourly time slot (primary key)",
    ts_date: "date of hourly time slot",
    ts_reference: sharedDescriptions.unique_reference,
    ts_quarterhours: "quarter hours occupied in the time slot (e.g., 1234 = all 4 quarters, 12 = first 2 quarters)",
    ts_duration: "duration of reservation in the time slot in hours",
    ts_timestamp_creation: "timestamp when timeslot record was created",
    ts_timestamp_modification: "timestamp when timeslot record was last modified",
    is_deleted: "flag if timeslot record was deleted (Y/N)",
    timeslot_id: "identifier of timeslot calculated based on res_itemobjectreference and res_userreference",
  },
  timeslots_1h_reservations: {
    timeslot_id: sharedDescriptions.timeslot_id,
    calendar_date: sharedDescriptions.calendar_date,
    day_of_week: sharedDescriptions.day_of_week,
    calendar_datetime: sharedDescriptions.calendar_datetime,
    timeslot_start: sharedDescriptions.timeslot_start,
    hour_of_day: sharedDescriptions.hour_of_day,
    location_id: sharedDescriptions.ts_location_id,
    location_class: sharedDescriptions.location_class,
    parent_location_id: sharedDescriptions.parent_location_id,
    parent_location_class: sharedDescriptions.parent_location_class,
    building_id: sharedDescriptions.building_id,
    floor_id: sharedDescriptions.floor_id,
    reservable_id: sharedDescriptions.reservable_id,
    reservable_unique_reference: sharedDescriptions.reso_unique_reference,
    reservable_reference: sharedDescriptions.reso_reference,
    reservable_name: "name of reservable",
    reservable_type: "type of reservable (ROOM, WORKPLACE, PARKING)",
    quarter_hours: "repeated quarter-hour coverage per reservation within the hourly timeslot",
    duration: "repeated reserved minutes per reservation within the hourly timeslot",
    reservation_id: "repeated immutable database identifier of reservation",
    reservation_reference: "repeated reservation reference for the user (booking number)",
    reservation_item_id: "repeated immutable database identifier of reservation item",
    reservation_item_nr: "repeated sequential number of item in a reservation (01, 02, 03 etc)",
    reservation_state: "reservation state for the timeslot (for example COMPLETED, CANCELLED, NO_SHOW, DELETE)",
    creation_timestamp: sharedDescriptions.creation_timestamp,
    modification_timestamp: "technical timestamp when the row was last updated, in ISO 8601 format and always in UTC",
  },
  // Views from definitions/axxerion/views/ (in alphabetical order as per directory listing)
  locations_v1: {
    location_name: "name of location",
    location_reference: sharedDescriptions.location_reference,
    location_class: sharedDescriptions.location_class,
    area_name: sharedDescriptions.area_name,
    area_reference: sharedDescriptions.area_reference,
    site_name: sharedDescriptions.site_name,
    site_reference: sharedDescriptions.site_reference,
    building_name: sharedDescriptions.building_name,
    building_reference: sharedDescriptions.building_reference,
    floor_name: sharedDescriptions.floor_name,
    floor_reference: sharedDescriptions.floor_reference,
    room_name: sharedDescriptions.room_name,
    room_reference: sharedDescriptions.room_reference,
    workplace_name: sharedDescriptions.workplace_name,
    workplace_reference: sharedDescriptions.workplace_reference,
    parking_place_name: sharedDescriptions.parking_place_name,
    parking_place_reference: sharedDescriptions.parking_place_reference,
    room_area_sqm: "area of room in sqm",
    room_category: "category of room",
    room_capacity: "capacity of room",
    space_class: sharedDescriptions.space_class,
    is_reservable: sharedDescriptions.is_reservable,
    location_id: sharedDescriptions.location_id,
    location_parent_id: sharedDescriptions.parent_location_id,
    area_id: sharedDescriptions.area_id,
    site_id: sharedDescriptions.site_id,
    building_id: sharedDescriptions.building_id,
    floor_id: sharedDescriptions.floor_id,
    room_id: sharedDescriptions.room_id,
    workplace_id: sharedDescriptions.workplace_id,
    parking_place_id: sharedDescriptions.parking_place_id,
  },
  reservables_v1: {
    reference: sharedDescriptions.reso_reference,
    unique_reference: sharedDescriptions.reso_unique_reference,
    type: "type of reservable",
    name: "name of reservable",
    capacity: sharedDescriptions.capacity,
    category_name: "name of reservable category",
    category_reference: "reference of reservable category",
    building_name: "building name where the reservable is located",
    building_reference: "building reference of reservable’s location.",
    floor_name: "floor name where the reservable is located",
    floor_reference: "floor reference of reservable’s location.",
    time_zone: "time zone name where reservable is located",
    reservable_id: sharedDescriptions.reservable_id,
    building_id: sharedDescriptions.building_id,
    floor_id: sharedDescriptions.floor_id,
    dwh_modified_timestamp: sharedDescriptions.dwh_modified_timestamp,
  },
  reservations_data_v1: {
    reservation_reference: sharedDescriptions.user_reference,
    reservation_unique_reference: sharedDescriptions.unique_reference,
    reservation_title: "title of reservation",
    reservation_remarks: "remarks of reservation",
    reservation_result: sharedDescriptions.result,
    reservation_participants_total: "total number of participants",
    reservation_start_datetime: "start date+time in local time zone",
    reservation_end_datetime: "end date+time in local time zone",
    reservation_creation_datetime: "date+time of creation in local time zone",
    reservation_cancel_datetime: "date+time of cancellation in local time zone",
    reservation_time_zone: "time zone name",
    reservation_creator_organization_name: sharedDescriptions.creator_organisation_name,
    reservation_organizer_organization_name: sharedDescriptions.organizer_organization_name,
    reservation_building_name: sharedDescriptions.building_name,
    reservation_building_reference: sharedDescriptions.building_reference,
    reservation_floor_name: sharedDescriptions.floor_name,
    reservation_floor_reference: sharedDescriptions.floor_reference,
    item_number: "sequential number of items in a reservation",
    item_name: "name of reserved item. Copy of reservable name at the time of reservation",
    item_description: "description of reserved item. Copy of reservable description at the time of reservation",
    item_reference: sharedDescriptions.reso_reference,
    item_type: "type of reserved item",
    item_category_name: "name of reserved item category",
    item_category_reference: "reference of reserved item category",
    item_quantity: "quantity of reserved item",
    item_capacity: "capacity (number of persons) of the reservable item",
    reservation_item_id: sharedDescriptions.item_id,
    reservation_id: sharedDescriptions.reservation_id,
    reservable_id: "identifier of a reservable (foreign key)",
    building_id: sharedDescriptions.building_id,
    floor_id: sharedDescriptions.floor_id,
    dwh_modified_timestamp: sharedDescriptions.dwh_modified_timestamp,
  },
  timeslots_15m_occupancy_data_v1: {
    timeslot_id: sharedDescriptions.timeslot_id,
    calendar_date: sharedDescriptions.calendar_date,
    day_of_week: sharedDescriptions.day_of_week,
    calendar_datetime: sharedDescriptions.calendar_datetime,
    timeslot_start: sharedDescriptions.timeslot_start,
    hour_of_day: sharedDescriptions.hour_of_day,
    creation_timestamp: sharedDescriptions.creation_timestamp,
    location_id: sharedDescriptions.ts_location_id,
    location_class: sharedDescriptions.location_class,
    parent_location_id: sharedDescriptions.parent_location_id,
    parent_location_class: sharedDescriptions.parent_location_class,
    building_id: sharedDescriptions.building_id,
    floor_id: sharedDescriptions.floor_id,
    space_class: sharedDescriptions.space_class,
    capacity: sharedDescriptions.ts_capacity,
    locations_total: sharedDescriptions.locations_total,
    locations_occupancy_monitored: sharedDescriptions.locations_occupancy_monitored,
    locations_occupied: sharedDescriptions.locations_occupied,
    rooms_total: sharedDescriptions.rooms_total,
    rooms_occupancy_monitored: sharedDescriptions.rooms_occupancy_monitored,
    workplaces_total: sharedDescriptions.workplaces_total,
    workplaces_occupancy_monitored: sharedDescriptions.workplaces_occupancy_monitored,
    occupancy_data_class: sharedDescriptions.occupancy_data_class,
    presence: sharedDescriptions.presence,
    headcount_peak: sharedDescriptions.headcount_peak,
    headcount_low: sharedDescriptions.headcount_low,
    headcount_average: sharedDescriptions.headcount_average,
    utilization_time: sharedDescriptions.utilization_time,
    utilization_rate: sharedDescriptions.utilization_rate_15m,
    efficiency_rate: sharedDescriptions.efficiency_rate_15m,
    occupancy_rate: sharedDescriptions.occupancy_rate_15m,
    business_day_start_hour: sharedDescriptions.business_day_start_hour,
    business_day_end_hour: sharedDescriptions.business_day_end_hour,
  },
  timeslots_1d_occupancy_data_v1: {
    timeslot_id: sharedDescriptions.timeslot_id,
    calendar_date: sharedDescriptions.calendar_date,
    day_of_week: sharedDescriptions.day_of_week,
    calendar_datetime: sharedDescriptions.calendar_datetime,
    timeslot_start: sharedDescriptions.timeslot_start,
    creation_timestamp: sharedDescriptions.creation_timestamp,
    location_id: sharedDescriptions.ts_location_id,
    location_class: sharedDescriptions.location_class,
    parent_location_id: sharedDescriptions.parent_location_id,
    parent_location_class: sharedDescriptions.parent_location_class,
    building_id: sharedDescriptions.building_id,
    floor_id: sharedDescriptions.floor_id,
    space_class: sharedDescriptions.space_class,
    capacity: sharedDescriptions.ts_capacity,
    locations_total: sharedDescriptions.locations_total,
    locations_occupancy_monitored: sharedDescriptions.locations_occupancy_monitored,
    locations_occupied: sharedDescriptions.locations_occupied,
    rooms_total: sharedDescriptions.rooms_total,
    rooms_occupancy_monitored: sharedDescriptions.rooms_occupancy_monitored,
    workplaces_total: sharedDescriptions.workplaces_total,
    workplaces_occupancy_monitored: sharedDescriptions.workplaces_occupancy_monitored,
    occupancy_data_class: sharedDescriptions.occupancy_data_class,
    presence: sharedDescriptions.presence,
    headcount_peak: sharedDescriptions.headcount_peak,
    headcount_low: sharedDescriptions.headcount_low,
    headcount_average: sharedDescriptions.headcount_average,
    utilization_time: sharedDescriptions.utilization_time,
    utilization_rate: sharedDescriptions.utilization_rate_avg,
    utilization_rate_peak: sharedDescriptions.utilization_rate_peak,
    utilization_rate_low: sharedDescriptions.utilization_rate_low,
    efficiency_rate: sharedDescriptions.efficiency_rate_avg,
    efficiency_rate_peak: sharedDescriptions.efficiency_rate_peak,
    efficiency_rate_low: sharedDescriptions.efficiency_rate_low,
    occupancy_rate: sharedDescriptions.occupancy_rate_avg,
    occupancy_rate_peak: sharedDescriptions.occupancy_rate_peak,
    occupancy_rate_low: sharedDescriptions.occupancy_rate_low,
    business_day_start_hour: sharedDescriptions.business_day_start_hour,
    business_day_end_hour: sharedDescriptions.business_day_end_hour,
    utilization_score: "utilization score for the timeslot",
    dwell_time_average: "average dwell time in the space",
    dwell_time_longest: "longest dwell time recorded",
    dwell_time_shortest: "shortest dwell time recorded",
  },
  timeslots_1h_occupancy_data_v1: {
    timeslot_id: sharedDescriptions.timeslot_id,
    calendar_date: sharedDescriptions.calendar_date,
    day_of_week: sharedDescriptions.day_of_week,
    calendar_datetime: sharedDescriptions.calendar_datetime,
    timeslot_start: sharedDescriptions.timeslot_start,
    hour_of_day: sharedDescriptions.hour_of_day,
    creation_timestamp: sharedDescriptions.creation_timestamp,
    location_id: sharedDescriptions.ts_location_id,
    location_class: sharedDescriptions.location_class,
    parent_location_id: sharedDescriptions.parent_location_id,
    parent_location_class: sharedDescriptions.parent_location_class,
    building_id: sharedDescriptions.building_id,
    floor_id: sharedDescriptions.floor_id,
    space_class: sharedDescriptions.space_class,
    capacity: sharedDescriptions.ts_capacity,
    locations_total: sharedDescriptions.locations_total,
    locations_occupancy_monitored: sharedDescriptions.locations_occupancy_monitored,
    locations_occupied: sharedDescriptions.locations_occupied,
    rooms_total: sharedDescriptions.rooms_total,
    rooms_occupancy_monitored: sharedDescriptions.rooms_occupancy_monitored,
    workplaces_total: sharedDescriptions.workplaces_total,
    workplaces_occupancy_monitored: sharedDescriptions.workplaces_occupancy_monitored,
    occupancy_data_class: sharedDescriptions.occupancy_data_class,
    presence: sharedDescriptions.presence,
    headcount_peak: sharedDescriptions.headcount_peak,
    headcount_low: sharedDescriptions.headcount_low,
    headcount_average: sharedDescriptions.headcount_average,
    utilization_time: sharedDescriptions.utilization_time,
    utilization_rate: sharedDescriptions.utilization_rate_avg,
    utilization_rate_peak: sharedDescriptions.utilization_rate_peak,
    utilization_rate_low: sharedDescriptions.utilization_rate_low,
    efficiency_rate: sharedDescriptions.efficiency_rate_avg,
    efficiency_rate_peak: sharedDescriptions.efficiency_rate_peak,
    efficiency_rate_low: sharedDescriptions.efficiency_rate_low,
    occupancy_rate: sharedDescriptions.occupancy_rate_avg,
    occupancy_rate_peak: sharedDescriptions.occupancy_rate_peak,
    occupancy_rate_low: sharedDescriptions.occupancy_rate_low,
    business_day_start_hour: sharedDescriptions.business_day_start_hour,
    business_day_end_hour: sharedDescriptions.business_day_end_hour,
  },
  sensor_data_v1: {
    sensor_id: sharedDescriptions.sensor_id,
    source: "source of sensor data",
    device_id: sharedDescriptions.device_id,
    timestamp: "timestamp in UTC timezone",
    value: "value registered by the sensor device",
    sensor_type: sharedDescriptions.sensor_type,
  },
  sensor_devices_v1: {
    sensor_history_id: "primary key",
    device_id: sharedDescriptions.device_id,
    device_external_id: "external identifier of a device",
    device_type: "type of device",
    device_name: "name of device",
    sensor_id: sharedDescriptions.sensor_id,
    source: "source of information",
    sensor_type: sharedDescriptions.sensor_type,
    version_number: "incremental version number (1, 2, 3, etc)",
    is_current: "flag that determines if the version is current or not",
    start_timestamp: "start timestamp of the version (in UTC)",
    end_timestamp: "end timestamp of the version (in UTC)",
    location_id: "unique identifier of the location where the device is installed",
    linked_location_ids: "list of monitored locations (indirect monitoring)",
    installed_timestamp: "timestamp when the device was installed in the location (in UTC)",
    is_disabled: "flag if the sensor is enabled or disabled",
    disabled_timestamp: "timestamp when the sensor was disabled (in UTC)",
    remark:  "remark",
  },
  service_requests_v1: {
    service_request_id: "id of service_request (primary key)",
    reference: "reference number",
    subject: "subject",
    external_reference: "external reference number",
    priority_name: "name of priority",
    priority_number: "number of priority",
    received_datetime: "date and time received in local timezone",
    due_datetime: "date and time due in local timezone",
    closed_datetime: "date and time closed in local timezone",
    service_type_name: "name of selected service type",
    service_type_reference: "reference of selected service type",
    service_type_l1: "first level service type in hierarchy",
    service_type_l2: "second level service type in hierarchy",
    service_type_l3: "third level service type in hierarchy",
    requester_organization_name: "organization name of the service requester",
    requester_organization_reference: "organization reference of the service requester",
    assigned_organization_name: "organization name of the assigned party",
    assigned_organization_reference: "organization reference of the assigned party",
    location_class: sharedDescriptions.location_class,
    status_name: "name of status",
    status_class: "class of status (OPEN or CLOSED)",
    elapsed_days: "number of calendar days between closed_datetime and received_datetime +1",
    region_code: "code of region",
    region_name: "name of region",
    site_code: "code of site",
    site_name: "name of site",
    building_code: "code of building",
    building_name: "name of building",
    floor_code: "code of floor",
    floor_name: "name of floor",
    room_code: "code of room",
    room_name: "name of room",
    service_type_id: "id of service_type (foreign key)",
    requester_organization_id: "id of requester organization (foreign key)",
    assigned_organization_id: "id of assigned organization (foreign key)",
    location_id: "id of location (foreign key)",
  },
};

function getColumnsDescriptions(table) {
  return schemas[table] ?? {};
}

function getTableNames(forDependencies) {
  const schemaKeys = Object.keys(schemas);
  let tables = schemaKeys.filter(name => !name.endsWith("_v1"));

  if (forDependencies) {
    return tables.filter(name => !name.startsWith("qsdb"));
  }

  return tables.map(name => `'${name}'`).join(", ");
}

function getViewNames(forDependencies, versionSuffix) {
  const schemaKeys = Object.keys(schemas);
  let views;
  if (versionSuffix) {
    views = schemaKeys.filter(name => name.endsWith(`_${versionSuffix}`));
  } else {
    views = schemaKeys.filter(name => name.endsWith("_v1"));
  }

  if (forDependencies) {
    return views;
  }

  return views.map(name => `'${name}'`).join(", ");
}

function stringToBoolean(str) {
  if (str == null) return false;
  const v = String(str).trim().toLowerCase();
  return v === "true";
}

module.exports = {
  getColumnsDescriptions,
  getTableNames,
  getViewNames,
  stringToBoolean,
};
